apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: transaction-service
  namespace: transaction
spec:
  project: default
  source:
    repoURL: https://github.com/himanshugvu/transaction-service.git
    targetRevision: HEAD
    path: base
  destination:
    server: https://kubernetes.default.svc
    namespace: transaction
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true