apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: transaction-service
  namespace: transaction
spec:
  host: transaction-service
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
