apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: transaction-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/himanshugvu/transaction-service.git
    targetRevision: HEAD
    path: k8s/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: transaction
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
