apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: transaction-service
  namespace: transaction
spec:
  replicas: 4
  selector:
    matchLabels:
      app: transaction-service
  template:
    metadata:
      labels:
        app: transaction-service
        version: v1  # Add the version label
    spec:
      containers:
        - name: transaction-service
          image: transaction-service:0.0.1-SNAPSHOT
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "0.5"
              memory: "512Mi"
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-XX:+UseContainerSupport -XX:MaxRAMPercentage=70.0 -Xss512k -XX:ReservedCodeCacheSize=150M -XX:MaxMetaspaceSize=64M -XX:MaxDirectMemorySize=10M"
  strategy:
    blueGreen:
      activeService: transaction-service-active
      previewService: transaction-service-preview
      autoPromotionEnabled: false
      prePromotionAnalysis:
        templates:
          - templateName: success-rate
        args:
          - name: service-name
            value: transaction-service-preview
      postPromotionAnalysis:
        templates:
          - templateName: success-rate
        args:
          - name: service-name
            value: transaction-service-active
