apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: transaction-service
  namespace: transaction
spec:
  replicas: 3
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: transaction-service
  template:
    metadata:
      labels:
        app: transaction-service
    spec:
      containers:
        - name: transaction-service
          image: himanshusuman/transaction-service:0.0.1-SNAPSHOT
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /health  # Adjust to your app's health endpoint
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 5
  strategy:
    canary:
      canaryService: transaction-service-preview
      stableService: transaction-service-active
      trafficRouting:
        istio:
          virtualService:
            name: transaction-vs
            routes:
              - primary
      steps:
        - setWeight: 20
        - pause: {duration: 30s}
        - setWeight: 40
        - pause: {duration: 30s}
        - setWeight: 60
        - pause: {duration: 30s}
        - setWeight: 80
        - pause: {duration: 30s}
