apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: transaction-service-stable
  namespace: transaction
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: "*"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: transaction-service-stable
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: transaction-service-canary
  namespace: transaction
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "0"
spec:
  rules:
    - host: "*"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: transaction-service-canary
                port:
                  number: 80
