apiVersion: v1
kind: Service
metadata:
  name: transaction-service-stable
  namespace: transaction
spec:
  selector:
    app: transaction-service
    rollouts-pod-template-hash: # Managed by Argo Rollouts
  ports:
  - name: http
    port: 80
    targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: transaction-service-canary
  namespace: transaction
spec:
  selector:
    app: transaction-service
    rollouts-pod-template-hash: # Managed by Argo Rollouts
  ports:
  - name: http
    port: 80
    targetPort: 8080
  type: ClusterIP
