apiVersion: v1
kind: Service
metadata:
  name: transaction-service-stable
  namespace: transaction
  labels:
    app: transaction-service
spec:
  selector:
    app: transaction-service
    rollouts-pod-template-hash: # Managed by Argo Rollouts
  ports:
    - port: 80 # Service port
      targetPort: http # Maps to the container port name (8080)
      protocol: TCP
      name: http
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: transaction-service-canary
  namespace: transaction
  labels:
    app: transaction-service
spec:
  selector:
    app: transaction-service
    rollouts-pod-template-hash: # Managed by Argo Rollouts
  ports:
    - port: 80 # Service port
      targetPort: http # Maps to the container port name (8080)
      protocol: TCP
      name: http
  type: ClusterIP
