apiVersion: v1
kind: Service
metadata:
  name: transaction-service
  namespace: transaction
  labels:
    app: transaction-service
spec:
  selector:
    app: transaction-service
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: transaction-service-canary
  namespace: transaction
  labels:
    app: transaction-service
    role: canary
spec:
  selector:
    app: transaction-service
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: transaction-service-stable
  namespace: transaction
  labels:
    app: transaction-service
    role: stable
spec:
  selector:
    app: transaction-service
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
