apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-service
  labels:
    app: transaction-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: transaction-service
  template:
    metadata:
      labels:
        app: transaction-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
      - name: transaction-service
        image: transaction-service:0.0.1-SNAPSHOT
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"  # Increased from 512Mi to 1Gi
          requests:
            cpu: "0.5"
            memory: "512Mi"  # Increased from 256Mi to 512Mi
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        env:
        - name: JAVA_TOOL_OPTIONS
          value: "-XX:+UseContainerSupport -XX:MaxRAMPercentage=70.0 -Xss512k -XX:ReservedCodeCacheSize=150M -XX:MaxMetaspaceSize=64M -XX:MaxDirectMemorySize=10M"
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
