apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-service
  labels:
    app: transaction-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: transaction-service
  template:
    metadata:
      labels:
        app: transaction-service
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/actuator/prometheus"
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: transaction-service
        image: himanshusman/transaction-service:0.0.1-SNAPSHOT
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "1Gi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        env:
        - name: BPL_JVM_THREAD_COUNT
          value: "100"
        - name: BPL_JVM_THREAD_STACK_SIZE
          value: "512K"
        - name: JAVA_TOOL_OPTIONS
          value: >-
            -XX:ReservedCodeCacheSize=128M 
            -XX:MaxMetaspaceSize=64M 
            -XX:MaxDirectMemorySize=10M 
            -XX:+UseContainerSupport 
            -XX:MaxRAMPercentage=65.0
            -Dspring.threads.virtual.enabled=true
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 15
